#!/usr/bin/perl

=head1 NAME

bin2xuv

=head1 SYNOPSIS

bin2xuv dump.bin >dump.xuv

=head1 DESCRIPTION

Converts plain binary files to XUV format.

=cut

use warnings;
use strict;

my $i = 0;
undef $/;
map { printf "@%06x %04x\r\n", $i++, $_ } unpack "v*", <>;
